# Generated by Django 4.2.15 on 2024-08-24 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('domicilio_calle', models.CharField(max_length=100)),
                ('domicilio_numero', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('cobertura_social', models.CharField(blank=True, max_length=100, null=True)),
                ('credencial', models.CharField(blank=True, max_length=100, null=True)),
                ('nro_historia_clinica', models.CharField(max_length=100, unique=True)),
                ('domicilio_calle', models.CharField(max_length=100)),
                ('domicilio_numero', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion', models.DurationField(default=datetime.timedelta(seconds=900))),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.paciente')),
            ],
        ),
    ]
