# Generated by Django 4.2.15 on 2024-09-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='valor_turno',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
