# Generated by Django 4.2.15 on 2024-10-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('bloqueado', 'Bloqueado'), ('sala-espera', 'En sala de espera'), ('consultorio', 'En consultorio'), ('atendido', 'Atendido'), ('ausente', 'Ausente')], default='disponible', max_length=20, null=True),
        ),
    ]
