# Generated by Django 4.2.15 on 2024-11-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
