# Generated by Django 4.2.15 on 2024-11-08 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_obrasocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='turnos.obrasocial'),
        ),
    ]
