# Generated by Django 4.2.15 on 2024-08-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_especialidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='duracion_turno',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
